-- 0010_origin_destination_specs.sql
-- 4 estándares nuevos de arándano desde los specs oficiales de agosto 2026:
--   "Quality Specs at Origin by label" (labels RR / FTF / Premium) y
--   "Quality Specs at Destination v1.2".
-- Esquema de 4 bandas A/B/C/D mapeado a bandas 1-4 del motor
--   (A/B → aprobado, C → condicional, D → rechazado).
--   Origen: A=US#1, B=US#1/US#2, C=National Market, D=Cull/Juice.
--   Destino: A=US#1, B=US#1.5, C=US#2, D=PAS/D&D.
-- "0 en todas las bandas" (no tolerado) se modela banda1=0-0 y banda4=0.01+.
-- Mapeos de nombre → defecto existente: Under ripe→immature_red,
--   Stem and Floral Remains→flower_remains, Dehydrated Fruit→shriveling,
--   Bruising/Mechanical Damage→bruises, Open Wounds→wounds, Lack of Bloom→no_bloom.
-- Defectos nuevos: insect_damage, leaky_berry, splits (+ template).
-- Limitación conocida: "Total % Critical" no se banda (el motor suma por familia
--   quality/condition); los críticos individuales (decay/mold/insect) sí se bandan.
-- Nota: estos specs reemplazan al pendiente "FTF Proceso" (Tolerancias FTF.xlsx era
--   una versión redondeada del label FTF de origen).

DECLARE @blue INT = (SELECT id FROM qc.commodities WHERE code='BLUEBERRY');

INSERT INTO qc.defects (commodity_id, code, label, family, value_type, unit)
SELECT @blue, v.code, v.label, 'condition', 'number', '%' FROM (VALUES
  ('insect_damage', N'Insect Damage (%)'),
  ('leaky_berry',   N'Leaky Berry (%)'),
  ('splits',        N'Splits (%)')
) v(code,label)
WHERE NOT EXISTS (SELECT 1 FROM qc.defects d WHERE d.commodity_id=@blue AND d.family='condition' AND d.code=v.code);

DECLARE @tpl INT = (SELECT id FROM qc.metric_templates WHERE commodity_id=@blue AND version=1);
INSERT INTO qc.template_defects (template_id, defect_id, required, order_index)
SELECT @tpl, d.id, 0, d.id
FROM qc.defects d
WHERE d.commodity_id=@blue AND d.code IN ('insect_damage','leaky_berry','splits')
  AND NOT EXISTS (SELECT 1 FROM qc.template_defects td WHERE td.template_id=@tpl AND td.defect_id=d.id);
GO

DECLARE @blue INT = (SELECT id FROM qc.commodities WHERE code='BLUEBERRY');

INSERT INTO qc.quality_standards (name, commodity_id, destination_id, active)
SELECT v.name, @blue, NULL, 1 FROM (VALUES
  (N'Origen RR'),(N'Origen FTF'),(N'Origen Premium'),(N'Destino FTF v1.2')
) v(name)
WHERE NOT EXISTS (SELECT 1 FROM qc.quality_standards s WHERE s.commodity_id=@blue AND s.name=v.name);

INSERT INTO qc.defect_tolerances (standard_id, defect_id, band, band_label, min_pct, max_pct)
SELECT s.id, d.id, t.band, t.lbl, t.mn, t.mx
FROM (VALUES
  (N'Origen RR','dust',1,'A',0,6.99),
  (N'Origen RR','dust',2,'B',7,9.99),
  (N'Origen RR','dust',3,'C',10,14.99),
  (N'Origen RR','dust',4,'D',15,NULL),
  (N'Origen RR','undersize',1,'A',0,6.99),
  (N'Origen RR','undersize',2,'B',7,9.99),
  (N'Origen RR','undersize',3,'C',10,14.99),
  (N'Origen RR','undersize',4,'D',15,NULL),
  (N'Origen RR','immature_red',1,'A',0,6.99),
  (N'Origen RR','immature_red',2,'B',7,9.99),
  (N'Origen RR','immature_red',3,'C',10,14.99),
  (N'Origen RR','immature_red',4,'D',15,NULL),
  (N'Origen RR','lack_of_color',1,'A',0,6.99),
  (N'Origen RR','lack_of_color',2,'B',7,9.99),
  (N'Origen RR','lack_of_color',3,'C',10,14.99),
  (N'Origen RR','lack_of_color',4,'D',15,NULL),
  (N'Origen RR','flower_remains',1,'A',0,6.99),
  (N'Origen RR','flower_remains',2,'B',7,9.99),
  (N'Origen RR','flower_remains',3,'C',10,14.99),
  (N'Origen RR','flower_remains',4,'D',15,NULL),
  (N'Origen RR','no_bloom',1,'A',0,6.99),
  (N'Origen RR','no_bloom',2,'B',7,9.99),
  (N'Origen RR','no_bloom',3,'C',10,14.99),
  (N'Origen RR','no_bloom',4,'D',15,NULL),
  (N'Origen RR','russet_scars',1,'A',0,6.99),
  (N'Origen RR','russet_scars',2,'B',7,9.99),
  (N'Origen RR','russet_scars',3,'C',10,14.99),
  (N'Origen RR','russet_scars',4,'D',15,NULL),
  (N'Origen RR','decay',1,'A',0,0),
  (N'Origen RR','decay',3,'C',0.01,0.5),
  (N'Origen RR','decay',4,'D',0.51,NULL),
  (N'Origen RR','mold',1,'A',0,0),
  (N'Origen RR','mold',3,'C',0.01,0.5),
  (N'Origen RR','mold',4,'D',0.51,NULL),
  (N'Origen RR','insect_damage',1,'A',0,0),
  (N'Origen RR','insect_damage',4,'D',0.01,NULL),
  (N'Origen RR','shriveling',1,'A',0,5),
  (N'Origen RR','shriveling',2,'B',5.01,10),
  (N'Origen RR','shriveling',3,'C',10.01,15),
  (N'Origen RR','shriveling',4,'D',15.01,NULL),
  (N'Origen RR','crushed',1,'A',0,1),
  (N'Origen RR','crushed',2,'B',1.01,2),
  (N'Origen RR','crushed',3,'C',2.01,3),
  (N'Origen RR','crushed',4,'D',3.01,NULL),
  (N'Origen RR','leaky_berry',1,'A',0,1),
  (N'Origen RR','leaky_berry',2,'B',1.01,2),
  (N'Origen RR','leaky_berry',3,'C',2.01,3),
  (N'Origen RR','leaky_berry',4,'D',3.01,NULL),
  (N'Origen RR','splits',1,'A',0,1),
  (N'Origen RR','splits',2,'B',1.01,2),
  (N'Origen RR','splits',3,'C',2.01,3),
  (N'Origen RR','splits',4,'D',3.01,NULL),
  (N'Origen RR','soft',1,'A',0,6.99),
  (N'Origen RR','soft',2,'B',7,9.99),
  (N'Origen RR','soft',3,'C',10,14.99),
  (N'Origen RR','soft',4,'D',15,NULL),
  (N'Origen RR','wounds',1,'A',0,1),
  (N'Origen RR','wounds',2,'B',1.01,3),
  (N'Origen RR','wounds',3,'C',3.01,5),
  (N'Origen RR','wounds',4,'D',5.01,NULL),
  (N'Origen RR','bruises',1,'A',0,6.99),
  (N'Origen RR','bruises',2,'B',7,9.99),
  (N'Origen RR','bruises',3,'C',10,14.99),
  (N'Origen RR','bruises',4,'D',15,NULL),
  (N'Origen RR','broken_skin',1,'A',0,6.99),
  (N'Origen RR','broken_skin',2,'B',7,9.99),
  (N'Origen RR','broken_skin',3,'C',10,14.99),
  (N'Origen RR','broken_skin',4,'D',15,NULL),
  (N'Origen RR','sum_quality',1,'A',0,10),
  (N'Origen RR','sum_quality',2,'B',10.01,20),
  (N'Origen RR','sum_quality',3,'C',20.01,25),
  (N'Origen RR','sum_quality',4,'D',25.01,NULL),
  (N'Origen RR','sum_condition',1,'A',0,5),
  (N'Origen RR','sum_condition',2,'B',5.01,10),
  (N'Origen RR','sum_condition',3,'C',10.01,20),
  (N'Origen RR','sum_condition',4,'D',20.01,NULL),
  (N'Origen FTF','dust',1,'A',0,5),
  (N'Origen FTF','dust',2,'B',5.01,6.99),
  (N'Origen FTF','dust',3,'C',7,9.99),
  (N'Origen FTF','dust',4,'D',10,NULL),
  (N'Origen FTF','undersize',1,'A',0,3),
  (N'Origen FTF','undersize',2,'B',3.01,4.99),
  (N'Origen FTF','undersize',3,'C',5,9.99),
  (N'Origen FTF','undersize',4,'D',10,NULL),
  (N'Origen FTF','immature_red',1,'A',0,2.99),
  (N'Origen FTF','immature_red',2,'B',3,4.99),
  (N'Origen FTF','immature_red',3,'C',5,9.99),
  (N'Origen FTF','immature_red',4,'D',10,NULL),
  (N'Origen FTF','lack_of_color',1,'A',0,2.99),
  (N'Origen FTF','lack_of_color',2,'B',3,4.99),
  (N'Origen FTF','lack_of_color',3,'C',5,9.99),
  (N'Origen FTF','lack_of_color',4,'D',10,NULL),
  (N'Origen FTF','flower_remains',1,'A',0,2.99),
  (N'Origen FTF','flower_remains',2,'B',3,4.99),
  (N'Origen FTF','flower_remains',3,'C',5,9.99),
  (N'Origen FTF','flower_remains',4,'D',10,NULL),
  (N'Origen FTF','no_bloom',1,'A',0,5),
  (N'Origen FTF','no_bloom',2,'B',5.01,6.99),
  (N'Origen FTF','no_bloom',3,'C',7,9.99),
  (N'Origen FTF','no_bloom',4,'D',10,NULL),
  (N'Origen FTF','russet_scars',1,'A',0,3),
  (N'Origen FTF','russet_scars',2,'B',3.01,4.99),
  (N'Origen FTF','russet_scars',3,'C',5,9.99),
  (N'Origen FTF','russet_scars',4,'D',10,NULL),
  (N'Origen FTF','decay',1,'A',0,0),
  (N'Origen FTF','decay',4,'D',0.01,NULL),
  (N'Origen FTF','mold',1,'A',0,0),
  (N'Origen FTF','mold',4,'D',0.01,NULL),
  (N'Origen FTF','insect_damage',1,'A',0,0),
  (N'Origen FTF','insect_damage',4,'D',0.01,NULL),
  (N'Origen FTF','shriveling',1,'A',0,3),
  (N'Origen FTF','shriveling',2,'B',3.01,5),
  (N'Origen FTF','shriveling',3,'C',5.01,10),
  (N'Origen FTF','shriveling',4,'D',10.01,NULL),
  (N'Origen FTF','crushed',1,'A',0,0),
  (N'Origen FTF','crushed',4,'D',0.01,NULL),
  (N'Origen FTF','leaky_berry',1,'A',0,0),
  (N'Origen FTF','leaky_berry',4,'D',0.01,NULL),
  (N'Origen FTF','splits',1,'A',0,1),
  (N'Origen FTF','splits',2,'B',1.01,2),
  (N'Origen FTF','splits',3,'C',2.01,3),
  (N'Origen FTF','splits',4,'D',3.01,NULL),
  (N'Origen FTF','soft',1,'A',0,2.99),
  (N'Origen FTF','soft',2,'B',3,4.99),
  (N'Origen FTF','soft',3,'C',5,9.99),
  (N'Origen FTF','soft',4,'D',10,NULL),
  (N'Origen FTF','wounds',1,'A',0,1),
  (N'Origen FTF','wounds',2,'B',1.01,3),
  (N'Origen FTF','wounds',3,'C',3.01,5),
  (N'Origen FTF','wounds',4,'D',5.01,NULL),
  (N'Origen FTF','bruises',1,'A',0,3),
  (N'Origen FTF','bruises',2,'B',3.01,4.99),
  (N'Origen FTF','bruises',3,'C',5,9.99),
  (N'Origen FTF','bruises',4,'D',10,NULL),
  (N'Origen FTF','broken_skin',1,'A',0,3),
  (N'Origen FTF','broken_skin',2,'B',3.01,4.99),
  (N'Origen FTF','broken_skin',3,'C',5,9.99),
  (N'Origen FTF','broken_skin',4,'D',10,NULL),
  (N'Origen FTF','sum_quality',1,'A',0,5),
  (N'Origen FTF','sum_quality',2,'B',5.01,10),
  (N'Origen FTF','sum_quality',3,'C',10.01,25),
  (N'Origen FTF','sum_quality',4,'D',25.01,NULL),
  (N'Origen FTF','sum_condition',1,'A',0,3),
  (N'Origen FTF','sum_condition',2,'B',3.01,5),
  (N'Origen FTF','sum_condition',3,'C',5.01,10),
  (N'Origen FTF','sum_condition',4,'D',10.01,NULL),
  (N'Origen Premium','dust',1,'A',0,0),
  (N'Origen Premium','dust',2,'B',0.01,1),
  (N'Origen Premium','dust',3,'C',1.01,2),
  (N'Origen Premium','dust',4,'D',2.01,NULL),
  (N'Origen Premium','undersize',1,'A',0,0),
  (N'Origen Premium','undersize',4,'D',0.01,NULL),
  (N'Origen Premium','immature_red',1,'A',0,0),
  (N'Origen Premium','immature_red',2,'B',0.01,2),
  (N'Origen Premium','immature_red',3,'C',2.01,4),
  (N'Origen Premium','immature_red',4,'D',4.01,NULL),
  (N'Origen Premium','lack_of_color',1,'A',0,2),
  (N'Origen Premium','lack_of_color',2,'B',2.01,4),
  (N'Origen Premium','lack_of_color',3,'C',4.01,6),
  (N'Origen Premium','lack_of_color',4,'D',6.01,NULL),
  (N'Origen Premium','flower_remains',1,'A',0,2),
  (N'Origen Premium','flower_remains',2,'B',2.01,4),
  (N'Origen Premium','flower_remains',3,'C',4.01,5),
  (N'Origen Premium','flower_remains',4,'D',5.01,NULL),
  (N'Origen Premium','no_bloom',1,'A',0,1),
  (N'Origen Premium','no_bloom',2,'B',1.01,2),
  (N'Origen Premium','no_bloom',3,'C',2.01,5),
  (N'Origen Premium','no_bloom',4,'D',5.01,NULL),
  (N'Origen Premium','russet_scars',1,'A',0,3),
  (N'Origen Premium','russet_scars',2,'B',3.01,6),
  (N'Origen Premium','russet_scars',3,'C',6.01,10),
  (N'Origen Premium','russet_scars',4,'D',10.01,NULL),
  (N'Origen Premium','decay',1,'A',0,0),
  (N'Origen Premium','decay',4,'D',0.01,NULL),
  (N'Origen Premium','mold',1,'A',0,0),
  (N'Origen Premium','mold',4,'D',0.01,NULL),
  (N'Origen Premium','insect_damage',1,'A',0,0),
  (N'Origen Premium','insect_damage',4,'D',0.01,NULL),
  (N'Origen Premium','shriveling',1,'A',0,1.5),
  (N'Origen Premium','shriveling',2,'B',1.51,2),
  (N'Origen Premium','shriveling',3,'C',2.01,4),
  (N'Origen Premium','shriveling',4,'D',4.01,NULL),
  (N'Origen Premium','crushed',1,'A',0,0),
  (N'Origen Premium','crushed',4,'D',0.01,NULL),
  (N'Origen Premium','leaky_berry',1,'A',0,0),
  (N'Origen Premium','leaky_berry',4,'D',0.01,NULL),
  (N'Origen Premium','splits',1,'A',0,0),
  (N'Origen Premium','splits',4,'D',0.01,NULL),
  (N'Origen Premium','soft',1,'A',0,0),
  (N'Origen Premium','soft',4,'D',0.01,NULL),
  (N'Origen Premium','wounds',1,'A',0,0.5),
  (N'Origen Premium','wounds',2,'B',0.51,1),
  (N'Origen Premium','wounds',3,'C',1.01,1.5),
  (N'Origen Premium','wounds',4,'D',1.51,NULL),
  (N'Origen Premium','bruises',1,'A',0,1),
  (N'Origen Premium','bruises',2,'B',1.01,2),
  (N'Origen Premium','bruises',3,'C',2.01,5),
  (N'Origen Premium','bruises',4,'D',5.01,NULL),
  (N'Origen Premium','broken_skin',1,'A',0,1),
  (N'Origen Premium','broken_skin',2,'B',1.01,2),
  (N'Origen Premium','broken_skin',3,'C',2.01,5),
  (N'Origen Premium','broken_skin',4,'D',5.01,NULL),
  (N'Origen Premium','sum_quality',1,'A',0,3),
  (N'Origen Premium','sum_quality',2,'B',3.01,5),
  (N'Origen Premium','sum_quality',3,'C',5.01,10),
  (N'Origen Premium','sum_quality',4,'D',10.01,NULL),
  (N'Origen Premium','sum_condition',1,'A',0,1),
  (N'Origen Premium','sum_condition',2,'B',1.01,3),
  (N'Origen Premium','sum_condition',3,'C',3.01,5),
  (N'Origen Premium','sum_condition',4,'D',5.01,NULL),
  (N'Destino FTF v1.2','dust',1,'A',0,6.99),
  (N'Destino FTF v1.2','dust',2,'B',7,9.99),
  (N'Destino FTF v1.2','dust',3,'C',10,14.99),
  (N'Destino FTF v1.2','dust',4,'D',15,NULL),
  (N'Destino FTF v1.2','undersize',1,'A',0,6.99),
  (N'Destino FTF v1.2','undersize',2,'B',7,9.99),
  (N'Destino FTF v1.2','undersize',3,'C',10,14.99),
  (N'Destino FTF v1.2','undersize',4,'D',15,NULL),
  (N'Destino FTF v1.2','immature_red',1,'A',0,6.99),
  (N'Destino FTF v1.2','immature_red',2,'B',7,9.99),
  (N'Destino FTF v1.2','immature_red',3,'C',10,14.99),
  (N'Destino FTF v1.2','immature_red',4,'D',15,NULL),
  (N'Destino FTF v1.2','lack_of_color',1,'A',0,6.99),
  (N'Destino FTF v1.2','lack_of_color',2,'B',7,9.99),
  (N'Destino FTF v1.2','lack_of_color',3,'C',10,14.99),
  (N'Destino FTF v1.2','lack_of_color',4,'D',15,NULL),
  (N'Destino FTF v1.2','flower_remains',1,'A',0,6.99),
  (N'Destino FTF v1.2','flower_remains',2,'B',7,9.99),
  (N'Destino FTF v1.2','flower_remains',3,'C',10,14.99),
  (N'Destino FTF v1.2','flower_remains',4,'D',15,NULL),
  (N'Destino FTF v1.2','no_bloom',1,'A',0,6.99),
  (N'Destino FTF v1.2','no_bloom',2,'B',7,9.99),
  (N'Destino FTF v1.2','no_bloom',3,'C',10,14.99),
  (N'Destino FTF v1.2','no_bloom',4,'D',15,NULL),
  (N'Destino FTF v1.2','russet_scars',1,'A',0,6.99),
  (N'Destino FTF v1.2','russet_scars',2,'B',7,9.99),
  (N'Destino FTF v1.2','russet_scars',3,'C',10,14.99),
  (N'Destino FTF v1.2','russet_scars',4,'D',15,NULL),
  (N'Destino FTF v1.2','decay',1,'A',0,0),
  (N'Destino FTF v1.2','decay',2,'B',0.01,0.5),
  (N'Destino FTF v1.2','decay',3,'C',0.51,2),
  (N'Destino FTF v1.2','decay',4,'D',2.01,NULL),
  (N'Destino FTF v1.2','mold',1,'A',0,0),
  (N'Destino FTF v1.2','mold',2,'B',0.01,0.5),
  (N'Destino FTF v1.2','mold',3,'C',0.51,2),
  (N'Destino FTF v1.2','mold',4,'D',2.01,NULL),
  (N'Destino FTF v1.2','insect_damage',1,'A',0,0),
  (N'Destino FTF v1.2','insect_damage',4,'D',0.01,NULL),
  (N'Destino FTF v1.2','shriveling',1,'A',0,5),
  (N'Destino FTF v1.2','shriveling',2,'B',5.01,10),
  (N'Destino FTF v1.2','shriveling',3,'C',10.01,15),
  (N'Destino FTF v1.2','shriveling',4,'D',15.01,NULL),
  (N'Destino FTF v1.2','crushed',1,'A',0,1),
  (N'Destino FTF v1.2','crushed',2,'B',1.01,2),
  (N'Destino FTF v1.2','crushed',3,'C',2.01,3),
  (N'Destino FTF v1.2','crushed',4,'D',3.01,NULL),
  (N'Destino FTF v1.2','leaky_berry',1,'A',0,1),
  (N'Destino FTF v1.2','leaky_berry',2,'B',1.01,2),
  (N'Destino FTF v1.2','leaky_berry',3,'C',2.01,3),
  (N'Destino FTF v1.2','leaky_berry',4,'D',3.01,NULL),
  (N'Destino FTF v1.2','splits',1,'A',0,1),
  (N'Destino FTF v1.2','splits',2,'B',1.01,2),
  (N'Destino FTF v1.2','splits',3,'C',2.01,3),
  (N'Destino FTF v1.2','splits',4,'D',3.01,NULL),
  (N'Destino FTF v1.2','soft',1,'A',0,6.99),
  (N'Destino FTF v1.2','soft',2,'B',7,9.99),
  (N'Destino FTF v1.2','soft',3,'C',10,14.99),
  (N'Destino FTF v1.2','soft',4,'D',15,NULL),
  (N'Destino FTF v1.2','wounds',1,'A',0,1),
  (N'Destino FTF v1.2','wounds',2,'B',1.01,3),
  (N'Destino FTF v1.2','wounds',3,'C',3.01,5),
  (N'Destino FTF v1.2','wounds',4,'D',5.01,NULL),
  (N'Destino FTF v1.2','bruises',1,'A',0,6.99),
  (N'Destino FTF v1.2','bruises',2,'B',7,9.99),
  (N'Destino FTF v1.2','bruises',3,'C',10,14.99),
  (N'Destino FTF v1.2','bruises',4,'D',15,NULL),
  (N'Destino FTF v1.2','broken_skin',1,'A',0,6.99),
  (N'Destino FTF v1.2','broken_skin',2,'B',7,9.99),
  (N'Destino FTF v1.2','broken_skin',3,'C',10,14.99),
  (N'Destino FTF v1.2','broken_skin',4,'D',15,NULL),
  (N'Destino FTF v1.2','sum_quality',1,'A',0,10),
  (N'Destino FTF v1.2','sum_quality',2,'B',10.01,20),
  (N'Destino FTF v1.2','sum_quality',3,'C',20.01,25),
  (N'Destino FTF v1.2','sum_quality',4,'D',25.01,NULL),
  (N'Destino FTF v1.2','sum_condition',1,'A',0,5),
  (N'Destino FTF v1.2','sum_condition',2,'B',5.01,10),
  (N'Destino FTF v1.2','sum_condition',3,'C',10.01,20),
  (N'Destino FTF v1.2','sum_condition',4,'D',20.01,NULL)
) t(std,dcode,band,lbl,mn,mx)
JOIN qc.quality_standards s ON s.commodity_id=@blue AND s.name=t.std
JOIN qc.defects d ON d.commodity_id=@blue AND d.code=t.dcode
WHERE NOT EXISTS (SELECT 1 FROM qc.defect_tolerances x WHERE x.standard_id=s.id AND x.defect_id=d.id AND x.band=t.band);
GO
